import { RouteInfo } from "./sidebar.metadata";

// Admin Module
export const AdminModuleRoutes: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/erp-admin-module/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "",
    title: "Admin Sub-Modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "",
    title: "Roles",
    moduleName: "admins",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-admin-module/admin/all-roles",
        title: "All Roles",
        moduleName: "admin",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "/erp-admin-module/admin/manage-roles",
        title: "Manage Roles",
        moduleName: "admin",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Users",
    moduleName: "user-management",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-admin-module/admin/all-users",
        title: "All Users",
        moduleName: "user-management",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "/erp-admin-module/admin/manage-users",
        title: "Manage Users",
        moduleName: "user-management",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },
  {
    path: "/erp-admin-module/admin/login-sessions",
    title: "Login Sessions",
    moduleName: "admin",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
];

export const ErpHrModuleRoutes: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/erp-hr/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "erp-hr/hradmin/job-management",
    title: "Job Management",
    moduleName: "job-management",
    iconType: "",
    icon: "user-plus",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "erp-hr/hradmin/job-management/job-posting",
        title: "Job Posting",
        moduleName: "job-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "erp-hr/hradmin/job-management/application-management",
        title: "Application Management",
        moduleName: "job-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "erp-hr/hradmin/job-management/interview-management",
        title: "Interview Management",
        moduleName: "job-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      }
    ],
  },

  {
    path: "erp-hr/hradmin/employee-management",
    title: "Employee Management",
    moduleName: "employee-management",
    iconType: "",
    icon: "users",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "erp-hr/hradmin/employee-management/employee-creation",
        title: "Employee Creation",
        moduleName: "employee-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "erp-hr/hradmin/employee-management/uploads",
        title: "Uploads",
        moduleName: "employee-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "erp-hr/hradmin/employee-management/employee-status",
        title: "Employee Status",
        moduleName: "employee-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },
  {
    path: "erp-hr/hradmin/leave-management",
    title: "Leave Management",
    moduleName: "leave-management",
    iconType: "",
    icon: "user-check",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "erp-hr/hradmin/leave-management/apply-leave",
        title: "Apply Leave",
        moduleName: "leave-management",
        iconType: "feather",
        icon: "chevrons-right",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "erp-hr/hradmin/leave-management/leave-planner",
        title: "Leave Planner",
        moduleName: "leave-management",
        iconType: "feather",
        icon: "chevrons-right",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "erp-hr/hradmin/leave-management/leave-reports",
        title: "Leave Reports",
        moduleName: "leave-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },

  {
    path: "erp-hr/hradmin/performance-management",
    title: "Performance Management",
    moduleName: "performance-management",
    iconType: "",
    icon: "user-check",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "erp-hr/hradmin/performance-management/kpi-details",
        title: "KPI Details",
        moduleName: "performance-management",
        iconType: "feather",
        icon: "chevrons-right",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "erp-hr/hradmin/performance-management/kpi-goal",
        title: "KPI Goal",
        moduleName: "performance-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "erp-hr/hradmin/performance-management/kpi-results",
        title: "KPI Results",
        moduleName: "performance-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },
];

export const SupplierManagementModuleRoutes: RouteInfo[] = [

  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/erp-suppliermanagement/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "",
    title: "Category management",
    moduleName: "sup-admin",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-suppliermanagement/sup-admin/all-categories",
        title: "All Categories",
        moduleName: "all-categories",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "/erp-suppliermanagement/sup-admin/manage-categories",
        title: "Manage Categories",
        moduleName: "manage-categories",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },

    ],
  },
  
  {
    path: "",
    title: "Supplier management",
    moduleName: "suppliermanagement",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-suppliermanagement/sup-admin/all-suppliers",
        title: "All Suppliers",
        moduleName: "all-suppliers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },

      {
        path: "/erp-suppliermanagement/sup-admin/manage-suppliers",
        title: "Manage Suppliers",
        moduleName: "manage-suppliers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },

      {
        path: "",
        title: "Company Profile",
        moduleName: "company-profile",
        iconType: "feather",
        icon: "home",
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ]

export const ErpProcurementModuleRoutes: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/erp-procurement-module/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "",
    title: "Procurement Committee",
    moduleName: "Procurement committee",
    iconType: "feather",
    icon: "align-justify",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-procurement-module/proc-admin/manage-committee",
        title: "Manage Committees",
        moduleName: "Procurement committee",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Requisitions",
    moduleName: "Requisitions",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-procurement-module/proc-admin/manage-requisitions",
        title: "Manage Requistions",
        moduleName: "requisitions",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "RFQs",
    moduleName: "RFQs",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-procurement-module/proc-admin/all-rfqs",
        title: "All RFQs",
        moduleName: "RFQs",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "/erp-procurement-module/proc-admin/manage-rfqs",
        title: "Manage RFQs",
        moduleName: "RFQs",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Receive Rfqs Applications",
    moduleName: "Receive Rfqs Applications",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-procurement-module/proc-admin/analyse-rfqs-applications",
        title: "Analyze RFQs Applications",
        moduleName: "Receive Rfqs Applications ",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },
  
  {
    path: "",
    title: "RFPs",
    moduleName: "RFPs",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-procurement-module/proc-admin/all-rfps",
        title: "All RFPs",
        moduleName: "RFPs",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "/erp-procurement-module/proc-admin/manage-rfps",
        title: "Manage RFPs",
        moduleName: "RFPs",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Receive Rfps Applications",
    moduleName: "Receive Rfps Applications",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-procurement-module/proc-admin/analyse-rfps-applications",
        title: "Analyze RFPs Applications",
        moduleName: "Receive Rfps Applications",
        iconType: "feather",
        icon: "",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["All"],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },
]
  
